- edivorce/apps/core/templates/partials/inline_question_determine_amount_to_pay.html
- edivorce/apps/core/templates/question/06_children_facts.html
- edivorce/apps/core/templates/question/06_children_income_expenses.html
- edivorce/apps/core/templates/question/06_children_what_for.html
- DIV-874
- DIV-875
- DIV-876
- DIV-879
- DIV-882
- DIV-886
- DIV-887
> Series of minor changes

- README.md
- edivorce/apps/core/templates/partials/review_user_responses.html
- edivorce/apps/core/templatetags/composites.py
- edivorce/apps/core/templatetags/format_utils.py
- edivorce/apps/core/templatetags/input_field.py
- edivorce/apps/core/templatetags/step_order.py
- edivorce/apps/core/templatetags/summary_format.py
- edivorce/apps/core/urls.py
- edivorce/apps/core/utils/step_completeness.py
- edivorce/apps/core/utils/user_response.py
- edivorce/apps/core/views/main.py
- edivorce/apps/core/views/system.py
- edivorce/settings/base.py
- edivorce/settings/local.py
- edivorce/urls.py
- requirements.txt
- wsgi.py
Updated Django from 1.8 to 1.11.15
> DIV-889: Updated Django to 1.11.15

- edivorce/apps/core/templates/legal.html
> DIV-890: Added text for Amici curiae to help page.

- .gitattributes
- jenkins/deploy-to-prod-Jenkinsfile
- jenkins/deploy-to-test-Jenkinsfile
- openshift/README.md
- openshift/backup-build.param
- openshift/backup-deploy.dev.param
- openshift/backup-deploy.overrides.sh
- openshift/backup-deploy.param
- openshift/backup-deploy.prod.param
- openshift/backup-deploy.test.param
- openshift/config/backup.conf
- openshift/settings.sh
- Add backup configurations and settings.
> Add support for backups

- edivorce/apps/core/static/js/functions.js
- edivorce/apps/core/templates/pdf/form1.html
- edivorce/apps/core/templates/pdf/form52.html
- edivorce/apps/core/templates/question/06_children_what_for.html
- edivorce/apps/core/templatetags/summary_format.py
- edivorce/apps/core/utils/question_step_mapping.py
- edivorce/apps/core/utils/step_completeness.py
- edivorce/apps/core/utils/user_response.py
- edivorce/fixtures/Question.json
DIV-915, DIV-916, and DIV-917
Updated question reveal options and fixed logic bugs
> DIV-912 Updated missing stretch of questions

- edivorce/apps/core/templates/question/06_children_what_for.html
- edivorce/apps/core/templatetags/summary_format.py
- edivorce/apps/core/utils/step_completeness.py
- edivorce/fixtures/Question.json
> DIV-912 Fixed the issues related to recent updates

- openshift/config/backup.conf
> Update backup configuration

- edivorce/apps/core/templates/pdf/form1.html
- edivorce/apps/core/templates/question/01_orders.html
- edivorce/apps/core/templates/question/06_children_facts.html
- edivorce/apps/core/templates/question/06_children_income_expenses.html
- edivorce/apps/core/templates/question/06_children_what_for.html
DIV-908: Added drop down questions on Step1.
DIV-909, 910, 930, 931: Updated wording of questions.
DIV-911: Added support text for who's the payor question.
DIV-920: Fixed Form 1 to show address without optional postal code.
DIV-937: Updated orders pertaining children section of step 1.
DIV-926,928: Updated Child support amount value on What for step 6.
> Div multiple updates

- edivorce/apps/core/static/js/functions.js
- edivorce/apps/core/static/js/main.js
- edivorce/apps/core/templates/question/06_children_facts.html
Updated text for Fact Sheet B, C, and D
Fixed IE 11 JS errors
> DIV-947, DIV-950

- edivorce/apps/core/static/js/main.js
- edivorce/apps/core/templates/partials/inline_question_determine_amount_to_pay.html
- edivorce/apps/core/templates/prequalification/step_04.html
- edivorce/apps/core/templates/question/06_children_facts.html
- edivorce/apps/core/templates/question/06_children_income_expenses.html
- edivorce/fixtures/Question.json
> DIV text and wording changes

- edivorce/apps/core/templates/pdf/form1.html
> DIV-969: Remove text from Form 1 Section 3

- edivorce/apps/core/templates/legal.html
Request for updated legal help text in the "Get Help" page.
The ticket doesn't contain links, but I found gov.bc.ca ones that should help point people in the right direction.
> DIV-976 - Change 'Get Help' text

- edivorce/apps/core/templates/pdf/form35.html
- edivorce/apps/core/views/pdf.py
- Switched checkboxes to Font Awesome ones, as the existing ones did not have a "checked" state, and we use FA in other places
- Added a new context variable `num_actual_children` that is a count of the number of children entered in Step 6
- Made one of the checkboxes conditional on children being entered, as requested by Kevin
> DIV-973 - Add default checkboxes in Form 35

- edivorce/apps/core/static/js/functions.js
- edivorce/apps/core/static/js/main.js
- edivorce/apps/core/templates/prequalification/step_04.html
- edivorce/apps/core/templates/question/01_orders.html
- edivorce/apps/core/templatetags/summary_format.py
- edivorce/apps/core/utils/question_step_mapping.py
- edivorce/fixtures/Question.json
DIV-971: Added additional prequal question for children.
DIV-975: Updated step 1 child support help text.
> DIV-971, 975 change request

- edivorce/apps/core/templates/success.html
Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>
> Update wording based on feedback.

- edivorce/apps/core/templates/success.html
Wording approved by GCPE.
Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>
> Update wording on success page based on feedback.

- edivorce/fixtures/Question.json
`last_name_born_you`, `last_name_before_married_you`, `last_name_born_spouse`, and `last_name_before_married_spouse` should all be optional, not required.
> Fix some questions so they're optional

- edivorce/apps/core/static/js/functions.js
- edivorce/apps/core/utils/conditional_logic.py
- edivorce/apps/core/utils/step_completeness.py
Address [DIV-1097](https://tickets.oxd.com/browse/DIV-1097) and fix big bug included in #86 that caused not-started pages to show required field errors.
> DIV-1097 - Required textbox fields accept spaces as valid input

- edivorce/apps/core/templates/prequalification/step_01.html
- edivorce/apps/core/templates/prequalification/step_02.html
- edivorce/apps/core/templates/prequalification/step_03.html
- edivorce/apps/core/templates/prequalification/step_04.html
- edivorce/apps/core/templates/prequalification/step_05.html
- edivorce/apps/core/templates/prequalification/step_06.html
DIV-1061 should have been updated after DIV-1016 was merged. Doing that now.
> DIV-1061: Fix merge. Update Complete status to Completed

- edivorce/apps/core/static/css/weasyprint.css
- edivorce/apps/core/templates/pdf/form52.html
Waiting for confirmation from Erin (in the ticket) that I added the correct signature.
> DIV-1150 - Updates to signature lines

- edivorce/apps/core/templates/pdf/form1.html
- edivorce/apps/core/templates/pdf/form37.html
- edivorce/apps/core/templates/pdf/form38.html
- edivorce/apps/core/templates/pdf/form52.html
- edivorce/apps/core/templates/question/06_children_what_for.html
- edivorce/apps/core/templatetags/format_utils.py
- edivorce/apps/core/templatetags/step_order.py
- edivorce/apps/core/tests/test_logic.py
Fix Next and Back button logic, update some references from `responses.claimant_children` to `derived.has_claimant_children`, fix form logic.
> DIV-1179: Fix some Children conditional logic

- edivorce/apps/core/templates/prequalification/step_01.html
Replaced the HTML escape characters with quotes.
> DIV-1251 - Fixed broken link to the Supreme court of B.C. website

- edivorce/apps/core/templates/partials/tooltips/court_order.html
- edivorce/apps/core/templates/partials/tooltips/file.html
- edivorce/apps/core/templates/partials/tooltips/forms/separation_agreement.html
- edivorce/apps/core/templates/partials/tooltips/online_package_number.html
I still have a few questions about ordering a certificate of divorce, but these should be ready.
> DIV-1177 - Updated tooltips based on Pat's feedback

- edivorce/apps/core/templates/dashboard/final_filing.html
Only show the instructions on how to scan documents if the user has chosen to file online.
> DIV-1321 - Disable scanning help line if not filing online

- edivorce/apps/core/templates/question/01_orders.html
Added tooltip to court order on Step 1 - What are you asking for?
> DIV-1320 - Added tooltip to Step 1

- edivorce/apps/core/templates/dashboard/final_filing.html
- edivorce/apps/core/templates/dashboard/print_form.html
- edivorce/apps/core/templates/partials/tooltips/forms/partys_certificate.html
- edivorce/apps/core/templates/partials/tooltips/forms/statement_of_information_for_corollary_relief_proceeedings.html
- edivorce/apps/core/templates/pdf/form1.html
- Changed F1 in Review and Print Forms to include Party's Certificate and to have the user sign it
- Added F102 to Additional Documents if the user wants spousal or child support
- Changed Lawyer's Certificate (s.9) to Party's Certificate and Lega; Adviser's Certificate in Form 1
Based on: https://vgi6tn.axshare.com/#id=alilxi&p=stage_3_-_review_forms&g=1
> DIV-1334 - Legislative changes to Review and Print Forms

- edivorce/apps/core/templates/dashboard/print_form.html
- edivorce/apps/core/templates/pdf/form1.html
- Escaped "&" characters in "Print & Sign"
- Removed lawyer's certificate
- Filled in names in Party Certificate
- Added second checkbox in Party Certificate for spouse
- Added signature lines for Party Certificate
> DIV-1334 - Additional changes to Form 1

- edivorce/apps/core/templates/partials/tooltips/habitual_residence.html
- edivorce/apps/core/templates/prequalification/step_02.html
- edivorce/apps/core/templates/question/02_claimant.html
- edivorce/apps/core/templates/question/03_respondent.html
Based on requirements.
Changed "ordinary residence" -> "habitual residence"
Changed "ordinarily resident" -> "habitually resident"
Also changed the filename of the partial html block to keep it consistent
> DIV-1337 - Replaced all references to ordinary residence

- edivorce/apps/core/templates/prequalification/step_06.html
- edivorce/apps/core/templates/question/06_children_income_expenses.html
- Pre-qualification Step 6
- Income and expenses, when they have Sole parenting responsibility
> DIV-1332 - A few more "custody" language changes

- edivorce/apps/core/templates/pdf/form1.html
- edivorce/apps/core/templates/prequalification/step_02.html
Updated a few remaining entries from "ordinarily resident" to "habitually resident" as per the new legislation.
This fix should go straight to production as soon as reasonable.
> Text updates

- edivorce/apps/core/templates/dashboard/final_filing.html
- edivorce/apps/core/templates/dashboard/next_steps.html
- edivorce/apps/core/templates/dashboard/print_form.html
- edivorce/apps/core/templates/question/02_claimant.html
- edivorce/apps/core/templates/question/03_respondent.html
- edivorce/apps/core/views/efiling.py
In order of change log below:
DIV-1301 - Incorrect page name referred on Final filing page for the page "Wait or Court File Number"
DIV-1264 - Increase the font size of the Your CSO Online Package # line
DIV-1339 - All external links should open in a new tab
DIV-1340 - Misleading help text for "How long have you lived in B.C" in both Claimant 1 and 2 questionnaire
> A bunch of minor corrections and fixes

- edivorce/apps/core/templates/partials/fact_sheets/fact_sheet_e.html
- edivorce/apps/core/templates/prequalification/step_05.html
- edivorce/apps/core/views/efiling.py
As requested by the Ministry
Also corrected one small typo
> DIV-1365: Remove French translation requirement text

- edivorce/apps/core/templates/dashboard/sign_file_options.html
Removed the divorce proceedings link in the instructions list
> DIV-1377: Removed the divorce proceedings link in the instructions list

- edivorce/apps/core/templates/dashboard/print_form.html
- Removed "Ready to Scan" when not e-filing
- Removed redundant Registration of Divorce
> Fix print forms

- edivorce/apps/core/utils/conditional_logic.py
Added a check for child support orders when testing for completeness of the protection order details.
I noticed that there could be a similar issue with the details of criminal proceedings, so added a check there too.
> Added check for child support orders

- edivorce/apps/core/static/js/filing.js
- edivorce/apps/core/templates/dashboard/final_filing.html
- edivorce/apps/core/templates/dashboard/initial_filing.html
- vue/package-lock.json
- vue/package.json
- vue/public/filing-uploader.html
- vue/src/components/Uploader/Image.vue
- vue/src/components/Uploader/ItemTile.vue
- vue/src/components/Uploader/ModalPreview.vue
- vue/src/components/Uploader/ProgressBar.vue
- vue/src/components/Uploader/Uploader.vue
- vue/src/pages/filing-uploader/FilingUploader.vue
- vue/src/pages/filing-uploader/main.js
- vue/src/utils/rotation.js
- vue/vue.config.js
- Updated to Vue 3 and dependencies
- Added linting to dev deps
- Refactoring
> DIV-1441: Updated to Vue3 and dependencies

- edivorce/apps/core/templates/dashboard/final_filing.html
- edivorce/apps/core/templates/partials/tooltips/forms/affidavit_of_no_marriage_certificate.html
I think I did this correctly, but just want your review.
When not filing online, all the forms are submitted in the final filing, including the "F30 No Marriage Affidavit" if they cannot provide the marriage certificate.
> DIV-1312: Added no marriage cert to final filing

- edivorce/apps/core/templates/pdf/form102.html
- edivorce/apps/core/templates/pdf/form35.html
- added checkbox for F102 in F35
- change to `<div>`s in F35 for better indentation (would not wrap correctly before)
- update title of F35
- update title of F102
> Legislative changes for September 2023

- COMPLIANCE.yaml
As required by repo-mountie. 
Dates from Status Reports during development
> Update PIA and STRA compliance

- vue/package-lock.json
Rollback FE updates, reapply Axios update using Node 14
> Rollback and reapply axios update

- edivorce/apps/core/utils/derived.py
- Picks the child support amount for incomes over $150k for the appropriate applicant.
- Adds that number to the amount shown on "What are you asking for"
> DIV-1492 / DIV-14: Added high income amount to proposed child support amount
